name: PR Preview

on:
  pull_request:
    branches: [ main, master ]

jobs:
  preview:
    name: Deploy Preview
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Build application
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL || secrets.DATABASE_URL }}
          NEXTAUTH_SECRET: ${{ secrets.NEXTAUTH_SECRET }}
          NEXTAUTH_URL: "https://preview-${{ github.event.number }}-your-app.vercel.app"
          GITHUB_CLIENT_ID: ${{ secrets.OAUTH_GITHUB_CLIENT_ID }}
          GITHUB_CLIENT_SECRET: ${{ secrets.OAUTH_GITHUB_CLIENT_SECRET }}

      - name: Deploy to Vercel Preview
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--env NEXTAUTH_URL=https://preview-${{ github.event.number }}-your-app.vercel.app'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domains: |
            preview-${{ github.event.number }}-your-app.vercel.app

      - name: Comment PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## 🚀 Preview Deployment
              
              Your preview deployment is ready!
              
              🔗 **Preview URL**: https://preview-${{ github.event.number }}-your-app.vercel.app
              
              📝 **Changes in this PR will be automatically deployed to this preview URL.**
              
              ---
              <sub>Powered by Vercel</sub>`
            })

  database-preview:
    name: Preview Database Setup
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'database-preview')
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma client
        run: npx prisma generate

      - name: Run preview database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }}

      - name: Seed preview database
        run: npm run db:seed
        env:
          DATABASE_URL: ${{ secrets.PREVIEW_DATABASE_URL }} 